version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: agency-api
    restart: unless-stopped
    ports:
      - '4000:4000'

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: agency-web
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - api
