// Typed error code constants used by HttpExceptionFilter.
import type { ErrorCode } from '@agency/shared';

export const ErrorCodes: Record<ErrorCode, ErrorCode> = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_USED: 'INVITE_USED',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  SOW_NOT_FOUND: 'SOW_NOT_FOUND',
  PAYROLL_RUN_LOCKED: 'PAYROLL_RUN_LOCKED',
  COMPENSATION_NOT_SET: 'COMPENSATION_NOT_SET',
  INSUFFICIENT_LEAVE_BALANCE: 'INSUFFICIENT_LEAVE_BALANCE',
  OWNER_ONLY: 'OWNER_ONLY',
};
