// [SHARED] Auditable sensitive actions tracked by AuditInterceptor.
export enum AuditAction {
  OWNER_VIEWED_CLIENT_FINANCIALS = 'OWNER_VIEWED_CLIENT_FINANCIALS',
  OWNER_VIEWED_SOW = 'OWNER_VIEWED_SOW',
  COMPENSATION_UPDATED = 'COMPENSATION_UPDATED',
  MEMBER_ROLE_CHANGED = 'MEMBER_ROLE_CHANGED',
  MEMBER_DEACTIVATED = 'MEMBER_DEACTIVATED',
  PAYROLL_RUN_CONFIRMED = 'PAYROLL_RUN_CONFIRMED',
  PAYROLL_RUN_PAID = 'PAYROLL_RUN_PAID',
  INVOICE_CREATED = 'INVOICE_CREATED',
  PAYMENT_LOGGED = 'PAYMENT_LOGGED',
  MILESTONE_RECEIVED = 'MILESTONE_RECEIVED',
  BRIEF_PUBLISHED = 'BRIEF_PUBLISHED',
  BANK_DETAILS_UPDATED = 'BANK_DETAILS_UPDATED',
}
