// [SHARED] Notification trigger types.
export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_COMMENTED = 'TASK_COMMENTED',
  TASK_MENTIONED = 'TASK_MENTIONED',
  LEAVE_REQUESTED = 'LEAVE_REQUESTED',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  LEAVE_REJECTED = 'LEAVE_REJECTED',
  PAYSLIP_GENERATED = 'PAYSLIP_GENERATED',
  ANNOUNCEMENT_POSTED = 'ANNOUNCEMENT_POSTED',
  MILESTONE_RECEIVED = 'MILESTONE_RECEIVED',
  INVOICE_OVERDUE = 'INVOICE_OVERDUE',
}
